/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkd.list;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


class LibraryTest {
    LinksList linksList = new LinksList();

    @Test
    public void testEmptyLinkedList() {
        String output = linksList.toString();
        assertEquals("NULL", output, "Must be NULL");
    }

    @Test
    public void testInsertToList() {
        linksList.insert(8);
        String output = linksList.toString();
        assertEquals(" { 7 } --> NULL", output, "Must be { 7 } --> Null");
    }

    @Test
    public void testHeadValue() {
        linksList.insert(7);
        Object output = linksList.head.value;
        assertEquals(7, output, "Must be 7");
    }


    LinksList numTest = new LinksList();

    @Test
    public void numTest() {
        numTest.insert(1);
        numTest.insert(2);
        numTest.insert(3);
        Throwable exception = assertThrows(IndexOutOfBoundsException.class, () -> numTest. (4) )
    }

    @Test

    public void numTest1() {
        numTest.insert(1);
        numTest.insert(2);
        numTest.insert(3);
        Throwable exception = assertThrows(IndexOutOfBoundsException.class, () -> numTest. (4) )
    }

    @Test

    public void numTest1() {
        numTest.insert(1);
        numTest.insert(2);
        numTest.insert(3);
        Throwable exception = assertThrows(IndexOutOfBoundsException.class, () -> numTest. (4) )

    }
}
