/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stakandqueue;

public class App {


    public static void main(String[] args){

        Stack<Integer> newStack=new Stack<>();{
            newStack.push(1);



            Node newNode = newStack.pop();
            System.out.println(newNode.value);
            System.out.println(newStack.isEmppty());



            Queue <Integer>  newqueue= new Queue<>();

            System.out.println(newqueue.isEmpty());
            System.out.println(newqueue.toString());

        }
    }
}
