/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stakandqueue;

public class App {


    public static void main(String[] args){

        Stack<Integer> newStack=new Stack<>();{
            newStack.push(1);
            newStack.push(2);

            System.out.println(newStack.pop().value); // 2
            System.out.println(newStack.isEmpty()); // false

            System.out.println(newStack.toString());

            System.out.println(newStack.pop().value); // 1

            System.out.println(newStack.isEmpty()); // true


//
            Queue <Integer>  newqueue= new Queue<>(); // create new Queue
            newqueue.enqueue(1);
            System.out.println(newqueue.dequeue());
            System.out.println(newqueue.isEmpty());
            newqueue.enqueue(2);
            System.out.println(newqueue.isEmpty());

//            Stackqueuepseudo stackqueuepseudo =new Stackqueuepseudo();
//            stackqueuepseudo.enqueue("abdallah");
//            stackqueuepseudo.enqueue("mohamed");
//            System.out.println(stackqueuepseudo.dequeue());
        }
    }
}
