/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package insertsort;

import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        int [] arr={8,4,23,42,16,15};
        System.out.println(new App().getGreeting());


    }

}
