/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

public class App {
    public String getGreeting() {

        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        BinarySearchTree<Integer> firstObj=new BinarySearchTree<>();
        firstObj.addFuction(11);
        firstObj.addFuction(12);
        firstObj.addFuction(20);
        System.out.println(firstObj.containsFunction(11));
        System.out.println(firstObj.containsFunction(12));
        System.out.println(firstObj.containsFunction(20));
        System.out.println(firstObj.containsFunction(15));
    }
}
