/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code28Sort;
import java.util.Arrays;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        int [] arr={1,4,5,2};
        System.out.println(Arrays.toString(quickSortFunction(arr,0,arr.length-1)));
    }
    public static int[] quickSortFunction(int[]arr,int left,int right){
        if (left<right){
            int position= partitionFunction(arr,left,right);
            quickSortFunction(arr,left,position-1);
            quickSortFunction(arr,position+1,right);
        }return arr;
    }
    public static  int partitionFunction(int[]arr,int left,int right){
        int pivot=arr[right];
        int low=left-1;
        for (int i = left; i <right ; i++) {
            if (arr[i]<=pivot){
                low++;
                swapFunction(arr,i,low);
            }
        }
        swapFunction(arr,right,low+1);
        return low+1;
    }
    public static void swapFunction(int[]arr,int i,int low){
        int temp=arr[i];
        arr[i]=arr[low];
        arr[low]=temp;
    }
}
