/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stakandqueue;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void test1(){
        Stack<Integer> test = new Stack<>();
        test.push(1);
        test.push(2);
        assertEquals(2,test.top.value);
        assertEquals(1,test.top.next.value);
    }
    @Test void testpop(){
        Stack<Integer> test= new Stack<>();
        test.push(1);
        Node<Integer> returnNode=test.pop();
        assertEquals(1,returnNode.value);

    }


}
