/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
class AppTest {
       @Test  void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
       @Test  void testSingleRoot(){
        BinarySearchTree<Integer> firstObj=new BinarySearchTree<>();
        firstObj.root=new Node(4);
        //firstObj.root(new Node(5));
        assertEquals(4,firstObj.root.nodeValue);
    }
        @Test  void testadd(){
        BinarySearchTree<Integer> firstObj=new BinarySearchTree<>();
        firstObj.addFuction(11);
        firstObj.addFuction(15);
        firstObj.addFuction(20);
        assertEquals(true,firstObj.containsFunction(11));
        assertEquals(true,firstObj.containsFunction(20));
        assertEquals(true,firstObj.containsFunction(15));
        assertEquals(false,firstObj.containsFunction(22));
    }
}
